# Generated by Django 2.0.2 on 2018-06-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('PR', 'Production'), ('R&D', 'Research and Development'), ('PU', 'Purchasing'), ('MA', 'Marketing'), ('HR', 'Human Resource Management'), ('AC', 'Accounting')], default='PR', max_length=2),
        ),
    ]
