# Generated by Django 2.0.2 on 2018-06-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='experience',
            new_name='years_experience',
        ),
    ]
